language: python
cache: pip
python:
  - "3.7"
  - "3.8"

install:
  - pip install -r requirements/test.txt

script: flake8 app/**/**/** tests/**/**/** && pytest -vv tests/*/* --cov=./app
after_success:
  - coveralls
